name: deploy
on:
  push:
    branches:
      - main

env:
  DOMAIN: www.aliciabytes.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Download Images
        run: utils/download-images.sh
      - name: Build the website
        run: npm run build
      - name: Deploy to Cloudflare pages
        uses: cloudflare/wrangler-action@7c01cc48d88a1f83b4716e0557c168854a9dcdb8 # v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy dist --project-name=aliciabytes-com
        timeout-minutes: 5
      - name: Submit sitemap to google
        run: curl -X GET https://www.google.com/ping?sitemap=https://${{ env.DOMAIN }}/sitemap-index.xml
      - name: Send urls to indexnow
        uses: bojieyang/indexnow-action@99fa50cf58d1ee519945b7db8ae71b0e60303ad7 # v2
        with:
          sitemap-location: "https://www.aliciabytes.com/sitemap-index.xml"
          key: ${{ secrets.INDEXNOW_KEY }}
