name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Download Images
        run: utils/download-images.sh
      - name: Build the website
        run: npm run build
      - name: Publish to Netlify
        id: netlify_publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=dist --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          timeout-minutes: 5
      - name: Print the deploy status
        uses: mshick/add-pr-comment@v2
        if: success() || failure()
        with:
          status: ${{ steps.netlify_publish.outcome }}
          message: |
            **Ooops, something went wrong.**
          message-success: |
            **Publishing to Netlify succeeded!**

            **Log Location:** ${{steps.netlify_publish.outputs.NETLIFY_LOGS_URL }}
            **Preview location:** ${{ steps.netlify_publish.outputs.NETLIFY_URL }}
            **Live location:** ${{ steps.netlify_publish.outputs.NETLIFY_LIVE_URL }}
          message-failure: |
            **Publishing to Netlify failed!**

            **Log Location:** ${{steps.netlify_publish.outputs.NETLIFY_LOGS_URL }}
